CREATE TABLE IF NOT EXISTS machines (
	machine_id CHAR(36) PRIMARY KEY,
	hardware_hash CHAR(64) NULL,
	first_seen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_seen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	trust_score FLOAT NOT NULL DEFAULT 1.0,
	blocked BOOLEAN NOT NULL DEFAULT FALSE,
	block_reason TEXT NULL
);

CREATE TABLE IF NOT EXISTS cache_creatures (
	entry_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	record_id INT UNSIGNED NOT NULL,
	locale VARCHAR(16) NOT NULL,
	content_hash CHAR(64) NOT NULL,
	game_build INT UNSIGNED NOT NULL,
	first_seen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	attestation_count INT UNSIGNED NOT NULL DEFAULT 1,
	is_consensus BOOLEAN NOT NULL DEFAULT FALSE,

	title VARCHAR(256) NOT NULL DEFAULT '',
	title_alt VARCHAR(256) NOT NULL DEFAULT '',
	cursor_name VARCHAR(64) NOT NULL DEFAULT '',
	leader BOOLEAN NOT NULL DEFAULT FALSE,
	creature_type INT UNSIGNED NOT NULL DEFAULT 0,
	creature_family INT UNSIGNED NOT NULL DEFAULT 0,
	classification INT UNSIGNED NOT NULL DEFAULT 0,
	num_displays INT UNSIGNED NOT NULL DEFAULT 0,
	total_probability FLOAT NOT NULL DEFAULT 0,
	hp_multiplier FLOAT NOT NULL DEFAULT 1,
	energy_multiplier FLOAT NOT NULL DEFAULT 1,
	movement_info_id INT NOT NULL DEFAULT 0,
	required_expansion INT UNSIGNED NOT NULL DEFAULT 0,
	tracking_quest_id INT UNSIGNED NOT NULL DEFAULT 0,
	vignette_id INT UNSIGNED NOT NULL DEFAULT 0,
	creature_class_mask INT UNSIGNED NOT NULL DEFAULT 0,
	creature_difficulty_id INT UNSIGNED NOT NULL DEFAULT 0,
	widget_parent_set_id INT UNSIGNED NOT NULL DEFAULT 0,
	widget_set_unit_condition_id INT UNSIGNED NOT NULL DEFAULT 0,

	names JSON NOT NULL,
	name_alts JSON NOT NULL,
	flags JSON NOT NULL,
	proxy_creature_ids JSON NOT NULL,
	displays JSON NOT NULL,
	quest_items JSON NOT NULL,
	currency_ids JSON NOT NULL,

	UNIQUE KEY uq_creature (record_id, locale, content_hash)
);

CREATE TABLE IF NOT EXISTS cache_quests (
	entry_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	record_id INT UNSIGNED NOT NULL,
	locale VARCHAR(16) NOT NULL,
	content_hash CHAR(64) NOT NULL,
	game_build INT UNSIGNED NOT NULL,
	first_seen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	attestation_count INT UNSIGNED NOT NULL DEFAULT 1,
	is_consensus BOOLEAN NOT NULL DEFAULT FALSE,

	quest_type INT UNSIGNED NOT NULL DEFAULT 0,
	quest_package_id INT UNSIGNED NOT NULL DEFAULT 0,
	content_tuning_id INT UNSIGNED NOT NULL DEFAULT 0,
	quest_sort_id INT NOT NULL DEFAULT 0,
	quest_info_id INT UNSIGNED NOT NULL DEFAULT 0,
	suggested_group_num INT UNSIGNED NOT NULL DEFAULT 0,
	reward_next_quest INT UNSIGNED NOT NULL DEFAULT 0,
	reward_xp_difficulty INT UNSIGNED NOT NULL DEFAULT 0,
	reward_xp_multiplier FLOAT NOT NULL DEFAULT 0,
	reward_money INT UNSIGNED NOT NULL DEFAULT 0,
	reward_money_difficulty INT UNSIGNED NOT NULL DEFAULT 0,
	reward_money_multiplier FLOAT NOT NULL DEFAULT 0,
	reward_bonus_money INT UNSIGNED NOT NULL DEFAULT 0,
	reward_display_spell_count INT UNSIGNED NOT NULL DEFAULT 0,
	reward_spell INT UNSIGNED NOT NULL DEFAULT 0,
	reward_honor_addition INT UNSIGNED NOT NULL DEFAULT 0,
	reward_honor_multiplier FLOAT NOT NULL DEFAULT 0,
	reward_artifact_xp_difficulty INT UNSIGNED NOT NULL DEFAULT 0,
	reward_artifact_xp_multiplier FLOAT NOT NULL DEFAULT 0,
	reward_artifact_category_id INT UNSIGNED NOT NULL DEFAULT 0,
	provided_item INT UNSIGNED NOT NULL DEFAULT 0,
	poi_continent INT UNSIGNED NOT NULL DEFAULT 0,
	poi_x FLOAT NOT NULL DEFAULT 0,
	poi_y FLOAT NOT NULL DEFAULT 0,
	poi_priority INT UNSIGNED NOT NULL DEFAULT 0,
	reward_title INT UNSIGNED NOT NULL DEFAULT 0,
	reward_arena_points INT UNSIGNED NOT NULL DEFAULT 0,
	reward_skill_line_id INT UNSIGNED NOT NULL DEFAULT 0,
	reward_num_skill_ups INT UNSIGNED NOT NULL DEFAULT 0,
	portrait_giver_display_id INT UNSIGNED NOT NULL DEFAULT 0,
	portrait_giver_mount_display_id INT UNSIGNED NOT NULL DEFAULT 0,
	portrait_turn_in_display_id INT UNSIGNED NOT NULL DEFAULT 0,
	portrait_model_scene_id INT UNSIGNED NOT NULL DEFAULT 0,
	reward_faction_flags INT UNSIGNED NOT NULL DEFAULT 0,
	accepted_sound_kit_id INT UNSIGNED NOT NULL DEFAULT 0,
	complete_sound_kit_id INT UNSIGNED NOT NULL DEFAULT 0,
	area_group_id INT UNSIGNED NOT NULL DEFAULT 0,
	time_allowed BIGINT UNSIGNED NOT NULL DEFAULT 0,
	num_objectives INT UNSIGNED NOT NULL DEFAULT 0,
	race_flags BIGINT UNSIGNED NOT NULL DEFAULT 0,
	expansion_id INT UNSIGNED NOT NULL DEFAULT 0,
	managed_world_state_id INT UNSIGNED NOT NULL DEFAULT 0,
	quest_session_bonus INT UNSIGNED NOT NULL DEFAULT 0,
	quest_giver_creature_id INT UNSIGNED NOT NULL DEFAULT 0,
	ready_for_translation BOOLEAN NOT NULL DEFAULT FALSE,
	reset_by_scheduler BOOLEAN NOT NULL DEFAULT FALSE,

	flags JSON NOT NULL,
	reward_fixed_items JSON NOT NULL,
	item_drop_items JSON NOT NULL,
	reward_choice_items JSON NOT NULL,
	faction_rewards JSON NOT NULL,
	currency_rewards JSON NOT NULL,
	reward_display_spells JSON NOT NULL,
	treasure_picker_ids JSON NOT NULL,
	treasure_picker_ids_2 JSON NOT NULL,
	objectives JSON NOT NULL,
	conditional_quest_descriptions JSON NOT NULL,
	conditional_quest_completions JSON NOT NULL,

	log_title TEXT NOT NULL,
	log_description TEXT NOT NULL,
	quest_description TEXT NOT NULL,
	area_description TEXT NOT NULL,
	portrait_giver_text TEXT NOT NULL,
	portrait_giver_name TEXT NOT NULL,
	portrait_turn_in_text TEXT NOT NULL,
	portrait_turn_in_name TEXT NOT NULL,
	quest_completion_log TEXT NOT NULL,

	UNIQUE KEY uq_quest (record_id, locale, content_hash)
);

CREATE TABLE IF NOT EXISTS cache_gameobjects (
	entry_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	record_id INT UNSIGNED NOT NULL,
	locale VARCHAR(16) NOT NULL,
	content_hash CHAR(64) NOT NULL,
	game_build INT UNSIGNED NOT NULL,
	first_seen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	attestation_count INT UNSIGNED NOT NULL DEFAULT 1,
	is_consensus BOOLEAN NOT NULL DEFAULT FALSE,

	type INT UNSIGNED NOT NULL DEFAULT 0,
	display_id INT UNSIGNED NOT NULL DEFAULT 0,
	icon VARCHAR(256) NOT NULL DEFAULT '',
	action VARCHAR(256) NOT NULL DEFAULT '',
	`condition` VARCHAR(256) NOT NULL DEFAULT '',
	scale FLOAT NOT NULL DEFAULT 1,
	content_tuning_id INT UNSIGNED NOT NULL DEFAULT 0,

	names JSON NOT NULL,
	game_data JSON NOT NULL,
	quest_items JSON NOT NULL,

	UNIQUE KEY uq_gameobject (record_id, locale, content_hash)
);

CREATE TABLE IF NOT EXISTS cache_pagetext (
	entry_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	record_id INT UNSIGNED NOT NULL,
	locale VARCHAR(16) NOT NULL,
	content_hash CHAR(64) NOT NULL,
	game_build INT UNSIGNED NOT NULL,
	first_seen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	attestation_count INT UNSIGNED NOT NULL DEFAULT 1,
	is_consensus BOOLEAN NOT NULL DEFAULT FALSE,

	next_page_text_id INT UNSIGNED NOT NULL DEFAULT 0,
	player_condition_id INT UNSIGNED NOT NULL DEFAULT 0,
	flags INT UNSIGNED NOT NULL DEFAULT 0,
	text TEXT NOT NULL,

	UNIQUE KEY uq_pagetext (record_id, locale, content_hash)
);

CREATE TABLE IF NOT EXISTS wdb_attestations (
	entity_type ENUM('creature', 'quest', 'gameobject', 'pagetext') NOT NULL,
	entry_id BIGINT UNSIGNED NOT NULL,
	machine_id CHAR(36) NOT NULL,
	submission_id CHAR(36) NOT NULL,
	attested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (entity_type, entry_id, machine_id)
);
