-- ============================================================
-- cache_creatures: drop JSON columns, add scalar columns
-- ============================================================
ALTER TABLE cache_creatures
	DROP COLUMN names,
	DROP COLUMN name_alts,
	DROP COLUMN flags,
	DROP COLUMN proxy_creature_ids,
	DROP COLUMN displays,
	DROP COLUMN quest_items,
	DROP COLUMN currency_ids,

	ADD COLUMN name_0 VARCHAR(256) NOT NULL DEFAULT '' AFTER widget_set_unit_condition_id,
	ADD COLUMN name_1 VARCHAR(256) NOT NULL DEFAULT '' AFTER name_0,
	ADD COLUMN name_2 VARCHAR(256) NOT NULL DEFAULT '' AFTER name_1,
	ADD COLUMN name_3 VARCHAR(256) NOT NULL DEFAULT '' AFTER name_2,

	ADD COLUMN name_alt_0 VARCHAR(256) NOT NULL DEFAULT '' AFTER name_3,
	ADD COLUMN name_alt_1 VARCHAR(256) NOT NULL DEFAULT '' AFTER name_alt_0,
	ADD COLUMN name_alt_2 VARCHAR(256) NOT NULL DEFAULT '' AFTER name_alt_1,
	ADD COLUMN name_alt_3 VARCHAR(256) NOT NULL DEFAULT '' AFTER name_alt_2,

	ADD COLUMN flag_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER name_alt_3,
	ADD COLUMN flag_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER flag_0,

	ADD COLUMN proxy_creature_id_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER flag_1,
	ADD COLUMN proxy_creature_id_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER proxy_creature_id_0,

	ADD COLUMN display_id_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER proxy_creature_id_1,
	ADD COLUMN display_scale_0 FLOAT NOT NULL DEFAULT 0 AFTER display_id_0,
	ADD COLUMN display_probability_0 FLOAT NOT NULL DEFAULT 0 AFTER display_scale_0,
	ADD COLUMN display_id_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER display_probability_0,
	ADD COLUMN display_scale_1 FLOAT NOT NULL DEFAULT 0 AFTER display_id_1,
	ADD COLUMN display_probability_1 FLOAT NOT NULL DEFAULT 0 AFTER display_scale_1,
	ADD COLUMN display_id_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER display_probability_1,
	ADD COLUMN display_scale_2 FLOAT NOT NULL DEFAULT 0 AFTER display_id_2,
	ADD COLUMN display_probability_2 FLOAT NOT NULL DEFAULT 0 AFTER display_scale_2,
	ADD COLUMN display_id_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER display_probability_2,
	ADD COLUMN display_scale_3 FLOAT NOT NULL DEFAULT 0 AFTER display_id_3,
	ADD COLUMN display_probability_3 FLOAT NOT NULL DEFAULT 0 AFTER display_scale_3,

	ADD COLUMN quest_item_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER display_probability_3,
	ADD COLUMN quest_item_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER quest_item_0,
	ADD COLUMN quest_item_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER quest_item_1,
	ADD COLUMN quest_item_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER quest_item_2,
	ADD COLUMN quest_item_4 INT UNSIGNED NOT NULL DEFAULT 0 AFTER quest_item_3,
	ADD COLUMN quest_item_5 INT UNSIGNED NOT NULL DEFAULT 0 AFTER quest_item_4,

	ADD COLUMN currency_id_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER quest_item_5,
	ADD COLUMN currency_id_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER currency_id_0;

-- ============================================================
-- cache_quests: drop JSON columns, add scalar columns
-- ============================================================
ALTER TABLE cache_quests
	DROP COLUMN flags,
	DROP COLUMN reward_fixed_items,
	DROP COLUMN item_drop_items,
	DROP COLUMN reward_choice_items,
	DROP COLUMN faction_rewards,
	DROP COLUMN currency_rewards,
	DROP COLUMN reward_display_spells,
	DROP COLUMN treasure_picker_ids,
	DROP COLUMN treasure_picker_ids_2,
	DROP COLUMN objectives,
	DROP COLUMN conditional_quest_descriptions,
	DROP COLUMN conditional_quest_completions,

	ADD COLUMN flag_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reset_by_scheduler,
	ADD COLUMN flag_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER flag_0,
	ADD COLUMN flag_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER flag_1,
	ADD COLUMN flag_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER flag_2,

	ADD COLUMN reward_fixed_item_id_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER flag_3,
	ADD COLUMN reward_fixed_item_qty_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_fixed_item_id_0,
	ADD COLUMN reward_fixed_item_id_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_fixed_item_qty_0,
	ADD COLUMN reward_fixed_item_qty_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_fixed_item_id_1,
	ADD COLUMN reward_fixed_item_id_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_fixed_item_qty_1,
	ADD COLUMN reward_fixed_item_qty_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_fixed_item_id_2,
	ADD COLUMN reward_fixed_item_id_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_fixed_item_qty_2,
	ADD COLUMN reward_fixed_item_qty_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_fixed_item_id_3,

	ADD COLUMN item_drop_item_id_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_fixed_item_qty_3,
	ADD COLUMN item_drop_item_qty_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER item_drop_item_id_0,
	ADD COLUMN item_drop_item_id_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER item_drop_item_qty_0,
	ADD COLUMN item_drop_item_qty_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER item_drop_item_id_1,
	ADD COLUMN item_drop_item_id_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER item_drop_item_qty_1,
	ADD COLUMN item_drop_item_qty_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER item_drop_item_id_2,
	ADD COLUMN item_drop_item_id_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER item_drop_item_qty_2,
	ADD COLUMN item_drop_item_qty_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER item_drop_item_id_3,

	ADD COLUMN reward_choice_item_id_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER item_drop_item_qty_3,
	ADD COLUMN reward_choice_item_qty_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_id_0,
	ADD COLUMN reward_choice_item_display_id_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_qty_0,
	ADD COLUMN reward_choice_item_id_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_display_id_0,
	ADD COLUMN reward_choice_item_qty_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_id_1,
	ADD COLUMN reward_choice_item_display_id_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_qty_1,
	ADD COLUMN reward_choice_item_id_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_display_id_1,
	ADD COLUMN reward_choice_item_qty_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_id_2,
	ADD COLUMN reward_choice_item_display_id_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_qty_2,
	ADD COLUMN reward_choice_item_id_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_display_id_2,
	ADD COLUMN reward_choice_item_qty_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_id_3,
	ADD COLUMN reward_choice_item_display_id_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_qty_3,
	ADD COLUMN reward_choice_item_id_4 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_display_id_3,
	ADD COLUMN reward_choice_item_qty_4 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_id_4,
	ADD COLUMN reward_choice_item_display_id_4 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_qty_4,
	ADD COLUMN reward_choice_item_id_5 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_display_id_4,
	ADD COLUMN reward_choice_item_qty_5 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_id_5,
	ADD COLUMN reward_choice_item_display_id_5 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_qty_5,

	ADD COLUMN faction_reward_id_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_choice_item_display_id_5,
	ADD COLUMN faction_reward_value_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_id_0,
	ADD COLUMN faction_reward_override_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_value_0,
	ADD COLUMN faction_reward_max_rank_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_override_0,
	ADD COLUMN faction_reward_id_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_max_rank_0,
	ADD COLUMN faction_reward_value_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_id_1,
	ADD COLUMN faction_reward_override_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_value_1,
	ADD COLUMN faction_reward_max_rank_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_override_1,
	ADD COLUMN faction_reward_id_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_max_rank_1,
	ADD COLUMN faction_reward_value_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_id_2,
	ADD COLUMN faction_reward_override_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_value_2,
	ADD COLUMN faction_reward_max_rank_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_override_2,
	ADD COLUMN faction_reward_id_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_max_rank_2,
	ADD COLUMN faction_reward_value_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_id_3,
	ADD COLUMN faction_reward_override_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_value_3,
	ADD COLUMN faction_reward_max_rank_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_override_3,
	ADD COLUMN faction_reward_id_4 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_max_rank_3,
	ADD COLUMN faction_reward_value_4 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_id_4,
	ADD COLUMN faction_reward_override_4 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_value_4,
	ADD COLUMN faction_reward_max_rank_4 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_override_4,

	ADD COLUMN currency_reward_id_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER faction_reward_max_rank_4,
	ADD COLUMN currency_reward_qty_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER currency_reward_id_0,
	ADD COLUMN currency_reward_id_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER currency_reward_qty_0,
	ADD COLUMN currency_reward_qty_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER currency_reward_id_1,
	ADD COLUMN currency_reward_id_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER currency_reward_qty_1,
	ADD COLUMN currency_reward_qty_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER currency_reward_id_2,
	ADD COLUMN currency_reward_id_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER currency_reward_qty_2,
	ADD COLUMN currency_reward_qty_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER currency_reward_id_3,

	ADD COLUMN reward_display_spell_id_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER currency_reward_qty_3,
	ADD COLUMN reward_display_spell_condition_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_display_spell_id_0,
	ADD COLUMN reward_display_spell_type_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_display_spell_condition_0,
	ADD COLUMN reward_display_spell_id_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_display_spell_type_0,
	ADD COLUMN reward_display_spell_condition_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_display_spell_id_1,
	ADD COLUMN reward_display_spell_type_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_display_spell_condition_1,
	ADD COLUMN reward_display_spell_id_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_display_spell_type_1,
	ADD COLUMN reward_display_spell_condition_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_display_spell_id_2,
	ADD COLUMN reward_display_spell_type_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_display_spell_condition_2,
	ADD COLUMN reward_display_spell_id_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_display_spell_type_2,
	ADD COLUMN reward_display_spell_condition_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_display_spell_id_3,
	ADD COLUMN reward_display_spell_type_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_display_spell_condition_3,

	ADD COLUMN treasure_picker_id_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER reward_display_spell_type_3,
	ADD COLUMN treasure_picker_id_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER treasure_picker_id_0,
	ADD COLUMN treasure_picker_id_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER treasure_picker_id_1,
	ADD COLUMN treasure_picker_id_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER treasure_picker_id_2,
	ADD COLUMN treasure_picker_id_4 INT UNSIGNED NOT NULL DEFAULT 0 AFTER treasure_picker_id_3,
	ADD COLUMN treasure_picker_id_5 INT UNSIGNED NOT NULL DEFAULT 0 AFTER treasure_picker_id_4,

	ADD COLUMN treasure_picker_id_2_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER treasure_picker_id_5,
	ADD COLUMN treasure_picker_id_2_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER treasure_picker_id_2_0,
	ADD COLUMN treasure_picker_id_2_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER treasure_picker_id_2_1,
	ADD COLUMN treasure_picker_id_2_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER treasure_picker_id_2_2,
	ADD COLUMN treasure_picker_id_2_4 INT UNSIGNED NOT NULL DEFAULT 0 AFTER treasure_picker_id_2_3,
	ADD COLUMN treasure_picker_id_2_5 INT UNSIGNED NOT NULL DEFAULT 0 AFTER treasure_picker_id_2_4;

-- ============================================================
-- cache_gameobjects: drop JSON columns, add scalar columns
-- ============================================================
ALTER TABLE cache_gameobjects
	DROP COLUMN names,
	DROP COLUMN game_data,
	DROP COLUMN quest_items,

	ADD COLUMN name_0 VARCHAR(256) NOT NULL DEFAULT '' AFTER content_tuning_id,
	ADD COLUMN name_1 VARCHAR(256) NOT NULL DEFAULT '' AFTER name_0,
	ADD COLUMN name_2 VARCHAR(256) NOT NULL DEFAULT '' AFTER name_1,
	ADD COLUMN name_3 VARCHAR(256) NOT NULL DEFAULT '' AFTER name_2,

	ADD COLUMN game_data_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER name_3,
	ADD COLUMN game_data_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_0,
	ADD COLUMN game_data_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_1,
	ADD COLUMN game_data_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_2,
	ADD COLUMN game_data_4 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_3,
	ADD COLUMN game_data_5 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_4,
	ADD COLUMN game_data_6 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_5,
	ADD COLUMN game_data_7 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_6,
	ADD COLUMN game_data_8 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_7,
	ADD COLUMN game_data_9 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_8,
	ADD COLUMN game_data_10 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_9,
	ADD COLUMN game_data_11 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_10,
	ADD COLUMN game_data_12 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_11,
	ADD COLUMN game_data_13 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_12,
	ADD COLUMN game_data_14 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_13,
	ADD COLUMN game_data_15 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_14,
	ADD COLUMN game_data_16 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_15,
	ADD COLUMN game_data_17 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_16,
	ADD COLUMN game_data_18 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_17,
	ADD COLUMN game_data_19 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_18,
	ADD COLUMN game_data_20 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_19,
	ADD COLUMN game_data_21 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_20,
	ADD COLUMN game_data_22 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_21,
	ADD COLUMN game_data_23 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_22,
	ADD COLUMN game_data_24 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_23,
	ADD COLUMN game_data_25 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_24,
	ADD COLUMN game_data_26 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_25,
	ADD COLUMN game_data_27 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_26,
	ADD COLUMN game_data_28 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_27,
	ADD COLUMN game_data_29 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_28,
	ADD COLUMN game_data_30 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_29,
	ADD COLUMN game_data_31 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_30,
	ADD COLUMN game_data_32 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_31,
	ADD COLUMN game_data_33 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_32,
	ADD COLUMN game_data_34 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_33,

	ADD COLUMN quest_item_0 INT UNSIGNED NOT NULL DEFAULT 0 AFTER game_data_34,
	ADD COLUMN quest_item_1 INT UNSIGNED NOT NULL DEFAULT 0 AFTER quest_item_0,
	ADD COLUMN quest_item_2 INT UNSIGNED NOT NULL DEFAULT 0 AFTER quest_item_1,
	ADD COLUMN quest_item_3 INT UNSIGNED NOT NULL DEFAULT 0 AFTER quest_item_2,
	ADD COLUMN quest_item_4 INT UNSIGNED NOT NULL DEFAULT 0 AFTER quest_item_3,
	ADD COLUMN quest_item_5 INT UNSIGNED NOT NULL DEFAULT 0 AFTER quest_item_4;

-- ============================================================
-- junction tables
-- ============================================================
CREATE TABLE IF NOT EXISTS cache_quest_objectives (
	quest_entry_id BIGINT UNSIGNED NOT NULL,
	objective_index TINYINT UNSIGNED NOT NULL,
	objective_id INT UNSIGNED NOT NULL DEFAULT 0,
	type INT UNSIGNED NOT NULL DEFAULT 0,
	storage_index TINYINT UNSIGNED NOT NULL DEFAULT 0,
	object_id INT UNSIGNED NOT NULL DEFAULT 0,
	amount INT UNSIGNED NOT NULL DEFAULT 0,
	flags INT UNSIGNED NOT NULL DEFAULT 0,
	flags2 INT UNSIGNED NOT NULL DEFAULT 0,
	percent_amount FLOAT NOT NULL DEFAULT 0,
	description TEXT NOT NULL,
	visual_effect_0 INT UNSIGNED NOT NULL DEFAULT 0,
	visual_effect_1 INT UNSIGNED NOT NULL DEFAULT 0,
	visual_effect_2 INT UNSIGNED NOT NULL DEFAULT 0,
	visual_effect_3 INT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (quest_entry_id, objective_index),
	FOREIGN KEY (quest_entry_id) REFERENCES cache_quests(entry_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cache_quest_conditional_texts (
	quest_entry_id BIGINT UNSIGNED NOT NULL,
	text_type ENUM('description', 'completion') NOT NULL,
	text_index TINYINT UNSIGNED NOT NULL,
	player_condition_id INT UNSIGNED NOT NULL DEFAULT 0,
	quest_giver_creature_id INT UNSIGNED NOT NULL DEFAULT 0,
	text TEXT NOT NULL,
	PRIMARY KEY (quest_entry_id, text_type, text_index),
	FOREIGN KEY (quest_entry_id) REFERENCES cache_quests(entry_id) ON DELETE CASCADE
);
